### ISSUE TITLE
config/esphome/nexxtender.yaml error

### ISSUE THREAD

**Issue by vanpeteghem** [geertmeersman/nexxtender#35]
Invalid YAML syntax: mapping values are not allowed here in "/config/esphome/secrets.yaml", line 2, column 10

t.av. geertmeersman .
Bedankt op voorhand voor de info.  Ik weet niet waar of hoe ik moet zoeken om die fout recht te zetten . Iedere hulp is welkom.

**Comment by geertmeersman** [comment]
Hoi, wat is je secrets.yaml inhoud? Heb je de waardes juist gezet?

**Comment by vanpeteghem** [comment]
Ik denk dat ik het verkeerde adm paswoord gebruik voor de esphome . Ik vond dat paswoord niet meer terug en heb het ota paswoord ingevuld misschien is dat de reden ? Hoe kan ik het ESP adm.password terugvinden ? Bedankt voor de info . Ik ben méér dan een leek in die materie .

**Comment by geertmeersman** [comment]
kan je me exact jouw secrets.yaml hier eens plakken? De waardes tussen de aanhalingstekens mag je weghalen

**Comment by vanpeteghem** [comment]
OKé,
esphome_admin_password:"3c3e876dd70eda5c6bd749ea8f5000e4"
wifi_ssid: "JOOST"
wifi_password: ""
esphome_api_key:=""
nexxtender_mac: ""
nexxtender_passkey: ""

**Comment by geertmeersman** [comment]
esphome_api_key:=""

geen =, enken een :

**Comment by vanpeteghem** [comment]
Hartelijke dank voor de info zal het onmiddellijk proberen .
