### ISSUE TITLE
The ESP home admin password 

### ISSUE THREAD

**Issue by vanpeteghem** [geertmeersman/nexxtender#36]
Mijnheer Meersman ik heb nog een probleempje met de installatie, ik weet mijn ESP home admin password niet meer. Is dit op te lossen ?  Ik heb zo'n Powerdale laadpaal gekocht in de tijd waarvan de firma nu failliet is en ik vond uw oplossing dan ook het ei van Columbus. Helaas is mijn kennis van computers niet zo toereikend als ik dacht ik ben ondertussen al 70. Maar een oplossing dringt zich op want ik kan niet meer laden dan 3Kwh met mijn laadpaal. Ik heb ondertussen een Home Assistant Green gekocht in de hoop dat de installatie wat eenvoudiger zou zijn, maar dat is het helaas niet. 

Groeten van Joost Van Peteghem

**Comment by geertmeersman** [comment]
Hoi Joost, geen probleem. Welk wachtwoord bedoel je juist? Waar gebruik je het? of wordt het je gevraagd

**Comment by vanpeteghem** [comment]
Het esphome_admin_password  dat zich bevindt in the secrets.yaml .  Is dat paswoord hetzelfde als dat waarmee je moet aanmelden op de Home Assistant Green want dat heb ik nog. Bedankt op voorhand voor de info. Ik zal niet nalaten om je een Duvel of twee te betalen als ik de toepassing werkbaar krijg. Groeten van Joost
