### ISSUE TITLE
substitutions

### ISSUE THREAD

**Issue by vanpeteghem** [geertmeersman/nexxtender#37]
FO ESPHome 2024.6.6
INFO Reading configuration /config/esphome/nexxtender-yaml.yaml...
ERROR Error while reading config: Invalid YAML syntax:

Duplicate key "substitutions"
  in "/config/esphome/nexxtender-yaml.yaml", line 59, column 1
NOTE: Previous declaration here:
  in "/config/esphome/nexxtender-yaml.yaml", line 1, column 1
Ik krijg deze melding als ik yaml file wil valideren en ik weet niet hoe dat op te lossen. Kan je me nogmaals helpen aub.  Gr. Joost

**Comment by geertmeersman** [comment]
Joost, kom anders eens op discord. De link staat op de readme pagina. Je mag me altijd daar een bericht sturen en dan bellen we misschien even, zal sneller gaan

**Comment by vanpeteghem** [comment]
Geert,
Moet ik die codes aanpassen of is dit louter ter info ?
Gr.Joost

Op do 25 jul 2024 09:40 schreef Geert Meersman ***@***.***>:
